### PR TITLE
Clean up the message parser

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Hum, this seems to have merging conflicts.

**Comment by ZeldaZach** [comment]
Yeah, I made a lot of changes to get it to work properly over the past few hours.

**Comment by ctrlaltca** [comment]
Uh-oh, it seems this is not something that's simple to merge.

**Comment by ZeldaZach** [comment]
Take your time, no rush on a fix :)

**Pull request closed without merging**
